const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog=[], record=null, page=null, selected=null, dirty=false, drawing=false, gesture=null, undo=[], saving=false, exportData=null, loadToken=0, toastTimer, materials=[];
const active=()=>record?.items.find(i=>i.id===selected);
const key=id=>`kurumi-corrections:${id}`;
const clone=x=>JSON.parse(JSON.stringify(x));
const roleLabels={correct:'久留美',wrong:'其他人物／说话人',mixed_speakers:'混入他人对白',no_visible_character:'人物不足以辨认',uncertain:'仍不确定'};
const clamp=n=>Math.max(0,Math.min(1000,n));
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',5000);}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败');return result;}
function snapshot(){undo.push(clone({items:record.items,notes:record.notes}));if(undo.length>60)undo.shift();}
function changed(boxes=false){dirty=true;if(boxes)record.reviewed=false;$('#save-status').textContent='有修改 · 已缓存浏览器';try{localStorage.setItem(key(page.id),JSON.stringify({base_revision:record.revision,record}));}catch{$('#save-status').textContent='浏览器缓存失败，请保存草稿';}renderTabs();}
function visiblePages(){return catalog.filter(p=>(!$('#volume').value||String(p.volume)===$('#volume').value)&&(!$('#only-pending').checked||!p.reviewed));}
function renderPageSelect(){const list=visiblePages();$('#page-select').innerHTML=list.map(p=>`<option value="${p.id}" ${page?.id===p.id?'selected':''}>${p.reviewed?'✓ ':''}第${p.volume}卷 / ${esc(p.source_file)}${p.auto_status==='ok'?` · ${p.auto_count}条`:''}</option>`).join('');}
function renderTabs(){$('#items').innerHTML=record.items.map((i,n)=>`<button data-item="${i.id}" class="${selected===i.id?'active':''}">素材 ${n+1}${i.speaker==='confirmed'?' ✓':''}</button>`).join('');$('#empty').hidden=record.items.length>0;$('#edit-form').hidden=!active();}
function renderBoxes(){const overlay=$('#overlay');overlay.classList.toggle('drawing',drawing);overlay.innerHTML=record.items.map((i,n)=>{const [x,y,x2,y2]=i.bbox;return `<div class="box ${i.id===selected?'selected':''}" data-box="${i.id}" style="left:${x/10}%;top:${y/10}%;width:${(x2-x)/10}%;height:${(y2-y)/10}%"><span>${n+1}</span>${i.id===selected?['nw','ne','sw','se'].map(h=>`<div class="handle ${h}" data-handle="${h}"></div>`).join(''):''}</div>`;}).join('');}
function preview(){const i=active(), source=$('#source'), canvas=$('#preview');if(!i||!source.complete||!source.naturalWidth)return;const [x,y,x2,y2]=i.bbox;const left=Math.round(x*source.naturalWidth/1000),top=Math.round(y*source.naturalHeight/1000),right=Math.round(x2*source.naturalWidth/1000),bottom=Math.round(y2*source.naturalHeight/1000);canvas.width=Math.max(1,right-left);canvas.height=Math.max(1,bottom-top);canvas.getContext('2d').drawImage(source,left,top,canvas.width,canvas.height,0,0,canvas.width,canvas.height);$('#coordinates').textContent=`范围 [${i.bbox.map(n=>n.toFixed(1)).join(', ')}] / 1000 · 原图截图 ${canvas.width} × ${canvas.height}px`;}
function renderForm(){renderTabs();const i=active();if(i){$('#quote').value=i.quote;$('#speaker').checked=i.speaker==='confirmed';$('#item-notes').value=i.notes||'';$('#box-reviewed').checked=!!i.box_reviewed;$('#quote-simplified').value=i.quote_simplified||'';$('#emotion-tags').value=(i.emotion_tags||[]).join('，');$('#meaning').value=i.meaning||'';$('#scenarios').value=i.scenarios||'';$('#material-status').textContent=`框体：${i.box_reviewed?'已复核':'待复核'} · OCR：${statusLabel(i.ocr_status)} · 说明：${statusLabel(i.metadata_status)}${i.ocr_error||i.metadata_error?' · '+(i.ocr_error||i.metadata_error):''}`;$('#ocr-text').textContent=i.ocr_text||'';$('#ocr-suggestion').hidden=!i.ocr_text;}$('#page-notes').value=record.notes;renderBoxes();preview();$('#add').classList.toggle('active',drawing);$('#add').textContent=drawing?'取消追加':'＋ 画框追加';}
async function navigate(id){if(saving||!id)return;const token=++loadToken;try{const result=await api('/api/page/'+id);if(token!==loadToken)return;page=result.page;record=result.correction;dirty=false;undo=[];drawing=false;gesture=null;let draft;try{draft=JSON.parse(localStorage.getItem(key(id))||'null');}catch{}if(draft?.base_revision===record.revision){record=draft.record;dirty=true;}else if(draft){toast('此页项目记录已有更新，已载入项目版本；旧浏览器草稿仍保留。');}selected=record.items[0]?.id||null;$('#page-title').textContent=`第 ${page.volume} 卷 · ${page.source_file}`;record.items.forEach(normalizeMaterial);$('#save-status').textContent=dirty?'已恢复未保存草稿':record.reviewed?'已完成整页复核':record.revision?'项目草稿已载入':'尚未复核';const hint=result.human_review;const hp=hint.page;$('#hints').textContent=[`原页确认：${hp.confirmed?'是':'否'}${hp.uncertain?'（仍有争议）':''}`,hp.notes?`原页意见：${hp.notes}`:'',hp.gold?`旧素材清单（可能与备注不一致，请按原图重新判断）：\n${hp.gold}`:'',...Object.entries(hint.candidates).map(([id,r])=>`${id}：归属=${roleLabels[r.role]||r.role}；${r.notes||'无备注'}`)].filter(Boolean).join('\n\n');$('#review-hints').hidden=!Object.keys(hp).length&&!Object.keys(hint.candidates).length;$('#auto-status').textContent=record.source_round==='round2'?'已载入优化识别结果':record.source_round==='round1'?'首轮候选，等待优化结果；也可直接人工修正':'尚无自动结果，仍可人工补框';$('#source').src='/api/image/'+id;$('#viewport').scrollTop=0;$('#viewport').scrollLeft=0;renderPageSelect();renderForm();}catch(e){toast(e.message);}}
const statusLabels={pending:'未处理',running:'处理中',recognized:'AI 已识别',confirmed:'人工已确认',generated:'AI 已生成',failed:'失败',stale:'待更新',needs_review:'识别存疑 · 待人工确认'};
const statusLabel=s=>statusLabels[s]||'未处理';
function normalizeMaterial(i){i.box_reviewed??=false;i.ocr_status??='pending';i.metadata_status??='pending';i.quote_source??='auto';i.annotation_source??='ai';i.emotion_tags??=[];i.meaning??='';i.scenarios??='';}
function invalidateBox(i){i.box_reviewed=false;i.ocr_status='stale';if(i.meaning||i.scenarios)i.metadata_status='stale';}
function invalidateMeaning(i){if(i.meaning||i.scenarios)i.metadata_status='stale';}
async function refreshCatalog(){const result=await api('/api/catalog');catalog=result.pages;materials=result.materials||[];$('#progress').textContent=`框体复核 ${catalog.filter(p=>p.reviewed).length}/${catalog.length} 页 · 自动识别 ${catalog.filter(p=>p.auto_status==='ok').length}/${catalog.length}`;$('#run-auto').textContent=result.job_running?'全量识别进行中…':'继续全量自动识别';$('#run-auto').disabled=result.job_running;const job=result.enrichment||{};for(const id of ['#batch-enrich','#checklist-batch','#ocr-current','#metadata-current'])$(id).disabled=!!job.running;$('#enrichment-progress').textContent=job.status==='idle'||!job.status?'先复核并保存裁剪框 → 一键 OCR 与简繁转换 → 生成情绪、台词含义与适用场景':`素材处理：${{running:'进行中',finished:'完成',stopped:'已停止',interrupted:'中断，可继续处理'}[job.status]||job.status} · ${job.completed||0} 完成 / ${job.total||0} 条 · ${job.failed||0} 失败 · ${job.skipped||0} 跳过${job.running?' · '+job.current:''}${job.error?' · '+job.error:''}`;renderPageSelect();if($('#checklist-dialog').open)renderChecklist();return result;}
function renderChecklist(){const doneOCR=i=>['recognized','confirmed'].includes(i.ocr_status),doneMeta=i=>['generated','confirmed'].includes(i.metadata_status);const counts=[['全部素材',materials.length],['框体已复核',materials.filter(i=>i.box_reviewed).length],['OCR 已完成',materials.filter(doneOCR).length],['说明已完成',materials.filter(doneMeta).length],['信息齐全',materials.filter(i=>i.ready).length]];$('#checklist-summary').innerHTML=counts.map(([label,n])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('');const filter=$('#checklist-filter').value;const rows=materials.filter(i=>filter==='all'||filter==='box'&&!i.box_reviewed||filter==='ocr'&&!doneOCR(i)||filter==='metadata'&&!doneMeta(i)||filter==='failed'&&(i.ocr_status==='failed'||i.metadata_status==='failed')||filter==='ready'&&i.ready);$('#checklist-rows').innerHTML=rows.map(i=>`<tr><td><button data-page="${esc(i.page_id)}" data-id="${esc(i.id)}">${esc(i.page_id)} / 素材 ${i.number}</button><div class="quote-summary">${esc(i.quote||'暂无台词')}</div>${i.error?`<small class="error">${esc(i.error)}</small>`:''}</td><td><span class="badge ${i.box_reviewed?'done':'pending'}">${i.box_reviewed?'已复核':'待复核'}</span></td><td><span class="badge ${esc(i.ocr_status)}">${statusLabel(i.ocr_status)}</span></td><td>${i.emotion_done?'✓ 已填写':'— 待填写'}</td><td>${i.meaning_done?'✓ 已填写':'— 待填写'}</td><td>${i.scenarios_done?'✓ 已填写':'— 待填写'}</td><td><span class="badge ${esc(i.metadata_status)}">${statusLabel(i.metadata_status)}</span></td></tr>`).join('')||'<tr><td colspan="7">当前筛选没有素材</td></tr>';}
function point(event){const rect=$('#stage').getBoundingClientRect();return [clamp((event.clientX-rect.left)/rect.width*1000),clamp((event.clientY-rect.top)/rect.height*1000)];}
function applyZoom(){
 const image=$('#source'),viewport=$('#viewport');
 if(!image.naturalWidth||!image.naturalHeight)return;
 const widthScale=viewport.clientWidth/image.naturalWidth,heightScale=viewport.clientHeight/image.naturalHeight;
 const mode=$('#zoom').value;
 const scale=mode==='page'?Math.min(widthScale,heightScale):mode==='height'?heightScale:mode==='width'?widthScale:widthScale*Number(mode);
 $('#stage').style.width=Math.max(1,Math.floor(image.naturalWidth*scale))+'px';
}
let zoomFrame;
new ResizeObserver(()=>{cancelAnimationFrame(zoomFrame);zoomFrame=requestAnimationFrame(applyZoom);}).observe($('#viewport'));
$('#overlay').addEventListener('pointerdown',event=>{if(saving||event.button!==0||!record||!$('#source').naturalWidth)return;event.preventDefault();const p=point(event),box=event.target.closest('[data-box]');if(drawing){gesture={kind:'draw',start:p,pointer:event.pointerId};}else if(box){selected=box.dataset.box;snapshot();gesture={kind:event.target.dataset.handle||'move',start:p,bbox:[...active().bbox],pointer:event.pointerId};renderForm();}else{selected=null;renderForm();return;}$('#overlay').setPointerCapture(event.pointerId);});
$('#overlay').addEventListener('pointermove',event=>{if(!gesture)return;const p=point(event),dx=p[0]-gesture.start[0],dy=p[1]-gesture.start[1];if(gesture.kind==='draw'){const b=[Math.min(p[0],gesture.start[0]),Math.min(p[1],gesture.start[1]),Math.max(p[0],gesture.start[0]),Math.max(p[1],gesture.start[1])];gesture.bbox=b;let el=$('.draft-box');if(!el){el=document.createElement('div');el.className='draft-box';$('#overlay').appendChild(el);}el.style.cssText=`left:${b[0]/10}%;top:${b[1]/10}%;width:${(b[2]-b[0])/10}%;height:${(b[3]-b[1])/10}%`;return;}const b=[...gesture.bbox],i=active();if(!i)return;if(gesture.kind==='move'){const x=Math.max(-b[0],Math.min(1000-b[2],dx)),y=Math.max(-b[1],Math.min(1000-b[3],dy));i.bbox=[b[0]+x,b[1]+y,b[2]+x,b[3]+y];}else{if(gesture.kind.includes('w'))b[0]=Math.min(b[2]-3,clamp(b[0]+dx));if(gesture.kind.includes('e'))b[2]=Math.max(b[0]+3,clamp(b[2]+dx));if(gesture.kind.includes('n'))b[1]=Math.min(b[3]-3,clamp(b[1]+dy));if(gesture.kind.includes('s'))b[3]=Math.max(b[1]+3,clamp(b[3]+dy));i.bbox=b;}renderBoxes();preview();});
function endGesture(event){if(!gesture)return;const g=gesture;gesture=null;if(g.kind==='draw'){if(g.bbox&&g.bbox[2]-g.bbox[0]>=3&&g.bbox[3]-g.bbox[1]>=3){snapshot();const i={id:'manual-'+crypto.randomUUID(),bbox:g.bbox,quote:'',speaker:'uncertain',notes:'',box_reviewed:false,ocr_status:'pending',metadata_status:'pending',emotion_tags:[],meaning:'',scenarios:''};record.items.push(i);selected=i.id;drawing=false;changed(true);}else toast('裁剪框太小，请重新画框。');}else{if(active()&&JSON.stringify(active().bbox)!==JSON.stringify(g.bbox))invalidateBox(active());changed(true);}if($('#overlay').hasPointerCapture(event.pointerId))$('#overlay').releasePointerCapture(event.pointerId);renderForm();}
$('#overlay').addEventListener('pointerup',endGesture);
$('#overlay').addEventListener('pointercancel',()=>{if(gesture?.kind!=='draw'&&active()&&gesture?.bbox)active().bbox=gesture.bbox;gesture=null;renderForm();});
$('#source').addEventListener('load',()=>{applyZoom();if(record){renderBoxes();preview();}});
$('#items').addEventListener('click',e=>{const b=e.target.closest('[data-item]');if(b){selected=b.dataset.item;renderForm();}});
$('#add').onclick=()=>{drawing=!drawing;renderForm();};
$('#delete').onclick=()=>{if(!active())return;snapshot();record.items=record.items.filter(i=>i.id!==selected);selected=record.items[0]?.id||null;changed(true);renderForm();};
$('#undo').onclick=()=>{if(!undo.length){toast('没有可撤销的操作。');return;}const previous=undo.pop();record.items=previous.items;record.notes=previous.notes;if(!active())selected=record.items[0]?.id||null;changed(true);renderForm();};
for(const [selector,field] of [['#quote','quote'],['#item-notes','notes']]) $(selector).addEventListener('input',()=>{if(!active())return;snapshot();active()[field]=$(selector).value;if(field==='quote'){active().quote_source='human';active().ocr_error='';active().ocr_status=active().quote.trim()?'confirmed':'pending';active().quote_simplified='';invalidateMeaning(active());}changed();});
$('#speaker').onchange=()=>{if(!active())return;snapshot();active().speaker=$('#speaker').checked?'confirmed':'uncertain';if(active().speaker!=='confirmed')active().box_reviewed=false;changed(true);};
$('#page-notes').oninput=()=>{snapshot();record.notes=$('#page-notes').value;changed();};
$('#zoom').onchange=()=>{applyZoom();$('#viewport').scrollTop=0;$('#viewport').scrollLeft=0;};
$('#volume').onchange=()=>{renderPageSelect();const first=visiblePages()[0];if(first)navigate(first.id);};
$('#only-pending').onchange=()=>{renderPageSelect();if(!visiblePages().some(p=>p.id===page?.id)&&visiblePages()[0])navigate(visiblePages()[0].id);};
$('#page-select').onchange=()=>navigate($('#page-select').value);
function relative(step){const list=visiblePages(),i=list.findIndex(p=>p.id===page?.id);const target=list[i+step];if(target)navigate(target.id);else toast('已经到达当前范围的边界。');}
$('#prev').onclick=()=>relative(-1);$('#next').onclick=()=>relative(1);
$('#next-pending').onclick=()=>{const start=catalog.findIndex(p=>p.id===page?.id);const target=[...catalog.slice(start+1),...catalog.slice(0,start+1)].find(p=>!p.reviewed&&(!$('#volume').value||String(p.volume)===$('#volume').value));if(target)navigate(target.id);else toast('当前范围全部复核完成。');};
async function save(reviewed){if(!record||saving)return false;const payload={...record,reviewed,items:record.items.map(i=>reviewed?{...i,speaker:'confirmed',box_reviewed:true}:i)};saving=true;document.querySelectorAll('button,input,textarea,select').forEach(e=>e.disabled=true);$('#overlay').style.pointerEvents='none';try{record=await api('/api/page/'+page.id,payload);dirty=false;localStorage.removeItem(key(page.id));$('#save-status').textContent=reviewed?'已完成整页复核':'草稿已保存到项目';renderForm();await refreshCatalog();toast(reviewed?(record.items.length?'本页框体复核已保存，可批量补齐台词与说明。':'已确认本页无素材。'):'草稿与截图已保存。');return true;}catch(e){toast(e.message);return false;}finally{saving=false;document.querySelectorAll('button,input,textarea,select').forEach(e=>e.disabled=false);$('#overlay').style.pointerEvents='';refreshCatalog().catch(()=>{});}}
$('#save-draft').onclick=()=>save(false);$('#complete').onclick=async()=>{const list=visiblePages(),index=list.findIndex(p=>p.id===page?.id),next=index>=0?list[index+1]:null;if(!(await save(true)))return;if(next)await navigate(next.id);else toast('当前范围已没有下一页，本页已保存。');};
$('#run-auto').onclick=async()=>{try{$('#run-auto').disabled=true;await api('/api/auto',{});await refreshCatalog();toast('全量识别已启动。成功页面自动跳过，人工修正不会被覆盖。');}catch(e){toast(e.message);$('#run-auto').disabled=false;}};
$('#export').onclick=async()=>{try{exportData=await api('/api/export',{});$('#report-count').textContent=`已复核 ${exportData.approved_pages} 页，待复核 ${exportData.pending_pages} 页；框已复核素材 ${exportData.items} 条，信息齐全 ${exportData.ready_items||0} 条。${dirty?'当前页未保存修改不会进入本次导出。':''}`;$('#report-text').textContent=exportData.report;$('#report-dialog').showModal();}catch(e){toast(e.message);}};
$('#close-report').onclick=()=>$('#report-dialog').close();
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#download-report').onclick=()=>download('人工修正报告.md',exportData.report,'text/markdown;charset=utf-8');
$('#download-catalogue').onclick=()=>download('corrected_catalog.json',JSON.stringify(exportData.catalogue,null,2),'application/json');
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function init(){try{await refreshCatalog();$('#volume').innerHTML='<option value="">全部</option>'+[...new Set(catalog.map(p=>p.volume))].map(v=>`<option value="${v}">第 ${v} 卷</option>`).join('');await navigate(catalog.find(p=>!p.reviewed)?.id||catalog[0].id);}catch(e){toast('加载失败：'+e.message);}}
async function syncCurrent(){if(!record||dirty||saving)return;const id=page.id;const result=await api('/api/page/'+id);if(!dirty&&!saving&&page.id===id&&result.correction.revision>record.revision){record=result.correction;renderForm();}}
setInterval(async()=>{if(saving)return;try{await syncCurrent();await refreshCatalog();}catch{}},3000);
init();

$('#box-reviewed').onchange=()=>{if(!active())return;if($('#box-reviewed').checked&&active().speaker!=='confirmed'){$('#box-reviewed').checked=false;toast('请先确认这是久留美的台词。');return;}snapshot();active().box_reviewed=$('#box-reviewed').checked;changed(true);};
for(const [selector,field] of [['#emotion-tags','emotion_tags'],['#meaning','meaning'],['#scenarios','scenarios']])$(selector).oninput=()=>{if(!active())return;snapshot();active()[field]=field==='emotion_tags'?$(selector).value.split(/[,，、]/).map(s=>s.trim()).filter(Boolean):$(selector).value;active().annotation_source='human';active().metadata_status=active().emotion_tags.length&&active().meaning.trim()&&active().scenarios.trim()?'confirmed':'pending';changed();};
$('#ocr-confirm').onclick=()=>{if(!active()?.quote.trim()){toast('请先填写或识别台词。');return;}snapshot();active().quote_source='human';active().ocr_error='';active().ocr_status='confirmed';changed();renderForm();};
$('#metadata-confirm').onclick=()=>{const i=active();if(!i?.emotion_tags.length||!i.meaning.trim()||!i.scenarios.trim()){toast('请补齐情绪标签、台词含义和适用场景。');return;}snapshot();i.annotation_source='human';i.metadata_status='confirmed';i.metadata_error='';changed();renderForm();};
async function enrich(mode,single=false){if(saving)return;const id=active()?.id;if(single&&!id)return;try{if(single&&mode==='ocr'&&(active().speaker!=='confirmed'||!active().box_reviewed)){snapshot();active().speaker='confirmed';active().box_reviewed=true;changed(true);renderForm();}if(dirty&&!(await save(record.reviewed)))return;await api('/api/enrich',{mode,...(single?{page_id:page.id,item_id:id}:{})});await refreshCatalog();toast(single?'处理已启动，完成后右侧自动更新；人工内容会保留。':'批量处理已启动，仅处理项目中已确认的框，跳过已完成项。');}catch(e){toast(e.message);}}
$('#ocr-current').onclick=()=>enrich('ocr',true);$('#metadata-current').onclick=()=>enrich('metadata',true);
$('#batch-enrich').onclick=()=>enrich('all');$('#checklist-batch').onclick=()=>enrich('all');
$('#open-checklist').onclick=async()=>{try{await refreshCatalog();renderChecklist();$('#checklist-dialog').showModal();}catch(e){toast(e.message);}};
$('#close-checklist').onclick=()=>$('#checklist-dialog').close();$('#checklist-filter').onchange=renderChecklist;
$('#checklist-rows').onclick=async e=>{const b=e.target.closest('[data-page]');if(!b)return;$('#checklist-dialog').close();$('#only-pending').checked=false;$('#volume').value='';await navigate(b.dataset.page);selected=b.dataset.id;renderPageSelect();renderForm();};
